name = "BayesOptim"
uuid = "f0d78ea2-d78e-4325-a3a8-acb8bb9c5755"
authors = ["Sakib Matin"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
